version: '3.8'
services:
  db:
    image: postgres:12.4-alpine
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: grandprinceess/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.21.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build/:/usr/share/nginx/html/
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  db_value:
